---
engines:
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
ratings:
  paths:
  - "**.py"
exclude_paths: 
  - "src/pygtk_chart/*"
  - "MANIFEST.in"
  - "src/OXM/images/**"
  - "src/OXM/images_map/*.png" 
  - "**.conf"
  - "**.xml"
  - "**.glade"
