version: 1.0.{build}

environment:
  PYTHON: C:\\Python27
  
install:
  - cmd: cinst gtk-runtime
  - cmd: appveyor DownloadFile "http://ftp.gnome.org/pub/GNOME/binaries/win32/pygtk/2.24/pygtk-all-in-one-2.24.2.win32-py2.7.msi"
  - cmd: msiexec /i pygtk-all-in-one-2.24.2.win32-py2.7.msi /qn /norestart /log pygtk-install.log TARGETDIR=C:\Python27 ALLUSERS=1
  - cmd: '%PYTHON%\\python.exe -m pip install wheel configobj raven'

build_script:
  - cmd: '%PYTHON%\\python.exe  setup.py bdist_wininst'

cache:
  - pygtk-all-in-one-2.24.2.win32-py2.7.msi

artifacts:
  - path: dist\openxenmanager-*.exe